SELECT SKU, SKU Description FROM INVENTORY;

SELECT SKU Description , SKU FROM INVENTORY;

SELECT WAREHOUSEID FROM INVENTORY;

SELECT Distinct WAREHOUSEID FROM INVENTORY;

SELECT WAREHOUSEID, SKU, SKU_DESCRIPTION, QUANTITYONHAND, QUANTITYONORDER FROM INVENTORY;

SELECT * FROM INVENTORY;

SELECT QUANTITYONHAND FROM INVENTORY WHERE QuantityOnHand > 0;

SELECT SKU, SKU_DESCRIPTION FROM INVENTORY WHERE QUANTITYONHAND = 0;

SELECT SKU, SKU_DESCRIPTION, WAREHOUSEID FROM INVENTORY WHERE QUANTITYONHAND = 0 ORDER BY WAREHOUSEID asc;

SELECT SKU, SKU_DESCRIPTION, WAREHOUSEID FROM  INVENTORY WHERE QUANTITYONHAND > 0 ORDER BY WAREHOUSEID desc, SKU asc;

SELECT SKU, SKU_Description, WarehouseID FROM INVENTORY WHERE QuantityOnHand = 0 AND QuantityOnOrder > 0 ORDER BY WarehouseID desc, SKU asc;

SELECT SKU, SKU_Description, WarehouseID FROM INVENTORY WHERE QuantityOnHand = 0 OR QuantityOnOrder = 0 ORDER BY WarehouseID desc, SKU asc; 

SELECT SKU, SKU_Description, WarehouseID, QuantityOnHand FROM INVENTORY WHERE QuantityOnHand > 1 AND QuantityOnHand < 10;

SELECT SKU, SKU_Description, WarehouseID, QuantityOnHand FROM INVENTORY WHERE QuantityOnHand BETWEEN 2 AND 9;

SELECT DISTINCT SKU, SKU_Description FROM INVENTORY WHERE SKU_Description LIKE 'Half-Dome%';

SELECT DISTINCT SKU, SKU_Description FROM INVENTORY WHERE SKU_Description LIKE '%Climb%';

SELECT DISTINCT SKU, SKU_Description FROM INVENTORY WHERE SKU_Description LIKE '__d%';

SELECT MIN(QuantityOnHand) AS MinQuantityOnHand, MAX(QuantityOnHand) AS MaxQuantityOnHand, AVG(QuantityOnHand) AS AvgQuantityOnHand, SUM(QuantityOnHand) AS SumQuantityOnHand, COUNT(QuantityOnHand) AS CountQuantityOnHand FROM INVENTORY;

SELECT WarehouseID, SUM(QuantityOnHand) AS TotalItemsOnHand FROM INVENTORY GROUP BY WarehouseID ORDER BY TotalItemsOnHand desc;

SELECT WarehouseID, SUM(QuantityOnHand) AS TotalItemsOnHandLT3 FROM INVENTORY WHERE QuantityOnHand < 3 GROUP BY WarehouseID ORDER BY TotalItemsOnHandLT3 desc;

SELECT WarehouseID, SUM(QuantityOnHand) AS TotalItemsOnHandLT3 FROM INVENTORY WHERE QuantityOnHand < 3 GROUP BY WarehouseID HAVING COUNT(*) < 2 ORDER BY TotalItemsOnHandLT3 DESC;
